apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goalixa-pwa

resources:
  - namespace.yaml
  - configmap.yaml
  - nginx-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml

images:
  - name: ghcr.io/goalixa/pwa
    newName: harbor.goalixa.com/goalixa-pwa/pwa
    newTag: latest  # Change this to specific commit SHA for each deployment
