apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goalixa-pwa

resources:
  - namespace.yaml
  - configmap.yaml
  - nginx-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml

images:
  - name: ghcr.io/goalixa/pwa
    newTag: latest

patches:
  - path: deployment-replicas.yaml

labels:
  - pairs:
      app.kubernetes.io/name: pwa
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: goalixa
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/env: production
